In [1]:
import numpy as np

### 1. Define states one and zero

In [2]:
zero=np.array([1,0])
one=np.array([0,1])

### 2. Define Hadamard gate as $2\times 2$ tensor

In [3]:
H=1/np.sqrt(2)*np.array(([1,1], [1,-1])).reshape(2,2)
print(H)
# np.einsum('i,ij->j', zero, H), np.einsum('i,ij->j', one, H)

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


### 3. Define CX gate as $2\times2\times2\times2$ tensor

In [4]:
CX=np.array(([1,0,0,0], [0,1,0,0], [0,0,0,1], [0,0,1,0])).reshape(2,2,2,2)
print(CX)
# zoCX=np.einsum('j,jkl->kl', one, np.einsum('i,ijkl->jkl', zero, CX))
# ooCX=np.einsum('j,jkl->kl', one, np.einsum('i,ijkl->jkl', one, CX))
# np.einsum('l,l->', one, np.einsum('k,kl->l', zero, zoCX)), \
# np.einsum('l,l->', zero, np.einsum('k,kl->l', one, ooCX)), 

[[[[1 0]
   [0 0]]

  [[0 1]
   [0 0]]]


 [[[0 0]
   [0 1]]

  [[0 0]
   [1 0]]]]


### 4. Lets apply H to $| 0 \rangle$

In [5]:
h=np.einsum('i,ij->j', zero, H)
h

array([0.70710678, 0.70710678])

### 5. Next apply CX gate to $|+\rangle |0\rangle$

In [6]:
L1=np.einsum('j,jkl->kl', zero, np.einsum('i,ijkl->jkl', h, CX))
print(L1)

[[0.70710678 0.        ]
 [0.         0.70710678]]


### 6. Apply SVD to L1, which is trivial

In [7]:
U, S, Vh = np.linalg.svd(L1, full_matrices=True)

U, S, Vh

(array([[1., 0.],
        [0., 1.]]),
 array([0.70710678, 0.70710678]),
 array([[1., 0.],
        [0., 1.]]))

### 7. Apply CX to $(V_h, |0\rangle)$

In [8]:
L2=np.einsum('k,iklm->ilm', one, np.einsum('ij,jklm->iklm', Vh, CX))
L2

array([[[0., 1.],
        [0., 0.]],

       [[0., 0.],
        [1., 0.]]])

### 8. Apply SVD to L2, reshape first

In [9]:
L2=L2.reshape(4,2)
U, S, Vh = np.linalg.svd(L2, full_matrices=False)
U.reshape(2,2,2),S,Vh

(array([[[ 0., -1.],
         [ 0.,  0.]],
 
        [[ 0.,  0.],
         [-1.,  0.]]]),
 array([1., 1.]),
 array([[-1., -0.],
        [-0., -1.]]))